const SalesOrderXmlData = (data) => {
  let {
    companyState,
    partyName,
    soNumber,
    itemDataForTally,

    expectedDeliveryDate,
  } = data;
  console.log(
    companyState,
    partyName,
    soNumber,
    itemDataForTally,

    "datat"
  );
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, "0"); // Months are 0-based, so add 1
  const day = String(today.getDate()).padStart(2, "0");

  let todaysDate = `${year}${month}${day}`;

  let myItems = "";
  let ledgerData = "";
  //   let totalAmount = 0;
  let totalTaxAmount = 0;
  let ledgerDataArray = [];
  itemDataForTally?.map((ele) => {
    console.log(ele, "datatata");
    myItems += `
    
    <ALLINVENTORYENTRIES.LIST>
      <STOCKITEMNAME>${ele?.itemNameForTally}</STOCKITEMNAME>
      <GSTOVRDNISREVCHARGEAPPL>&#4; Not Applicable</GSTOVRDNISREVCHARGEAPPL>
      <GSTOVRDNTAXABILITY>Exempt</GSTOVRDNTAXABILITY>
      <GSTSOURCETYPE>Stock Item</GSTSOURCETYPE>
      <GSTITEMSOURCE>${ele?.itemNameForTally}</GSTITEMSOURCE>
      <GSTOVRDNSTOREDNATURE/>
      <GSTOVRDNTYPEOFSUPPLY>Goods</GSTOVRDNTYPEOFSUPPLY>
      <GSTRATEINFERAPPLICABILITY>As per Masters/Company</GSTRATEINFERAPPLICABILITY>
      <GSTHSNINFERAPPLICABILITY>As per Masters/Company</GSTHSNINFERAPPLICABILITY>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
      <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
      <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
      <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
      <ISAUTONEGATE>No</ISAUTONEGATE>
      <ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
      <ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
      <ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
      <ISPRIMARYITEM>No</ISPRIMARYITEM>
      <ISSCRAP>No</ISSCRAP>
      <RATE>${ele?.rateForTally}/PCS</RATE>
      <AMOUNT>${ele?.rateForTally * ele?.quantityForTally}</AMOUNT>
      <ACTUALQTY> ${ele?.quantityForTally} PCS</ACTUALQTY>
      <BILLEDQTY> ${ele?.quantityForTally} PCS</BILLEDQTY>
      <BATCHALLOCATIONS.LIST>
       <GODOWNNAME>1Main Location</GODOWNNAME>
       <BATCHNAME>Primary Batch</BATCHNAME>
       <DESTINATIONGODOWNNAME>1Main Location</DESTINATIONGODOWNNAME>
       <INDENTNO>&#4; Not Applicable</INDENTNO>
       <ORDERNO>PI/24-25/${soNumber}</ORDERNO>
       <TRACKINGNUMBER>&#4; Not Applicable</TRACKINGNUMBER>
       <DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
       <AMOUNT>${ele?.rateForTally * ele?.quantityForTally}</AMOUNT>
       <ACTUALQTY> ${ele?.quantityForTally} PCS</ACTUALQTY>
       <BILLEDQTY> ${ele?.quantityForTally} PCS</BILLEDQTY>
      <ORDERDUEDATE JD="45428" P="${expectedDeliveryDate}">${expectedDeliveryDate}</ORDERDUEDATE>
       <ADDITIONALDETAILS.LIST>        </ADDITIONALDETAILS.LIST>
       <VOUCHERCOMPONENTLIST.LIST>        </VOUCHERCOMPONENTLIST.LIST>
      </BATCHALLOCATIONS.LIST>
      <ACCOUNTINGALLOCATIONS.LIST>
       <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
       <LEDGERNAME>Sales</LEDGERNAME>
       <GSTCLASS>&#4; Not Applicable</GSTCLASS>
       <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
       <LEDGERFROMITEM>No</LEDGERFROMITEM>
       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
       <ISPARTYLEDGER>No</ISPARTYLEDGER>
       <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
       <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
       <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
       <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
       <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
       <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
       <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
       <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
       <AMOUNT>${ele?.rateForTally * ele?.quantityForTally}</AMOUNT>
       <SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
       <BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
       <BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
       <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
       <OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
       <INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
       <DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
       <EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
       <RATEDETAILS.LIST>        </RATEDETAILS.LIST>
       <SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
       <CENVATDUTYALLOCATIONS.LIST>        </CENVATDUTYALLOCATIONS.LIST>
       <STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
       <EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
       <TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
       <TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
       <TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
       <VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
       <COSTTRACKALLOCATIONS.LIST>        </COSTTRACKALLOCATIONS.LIST>
       <REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
       <INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
       <VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
       <ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
       <TAXTYPEALLOCATIONS.LIST>        </TAXTYPEALLOCATIONS.LIST>
      </ACCOUNTINGALLOCATIONS.LIST>
      <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST>
       <GSTRATEDUTYHEAD>CGST</GSTRATEDUTYHEAD>
       <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
       <GSTRATE>  ${
         ele?.taxTypeForTally[0] === "CGST" ? ele?.taxPercentForTally[0] : ""
       }</GSTRATE>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
       <GSTRATEDUTYHEAD>SGST/UTGST</GSTRATEDUTYHEAD>
       <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
       <GSTRATE> ${
         ele?.taxTypeForTally[0] === "SGST" ||
         ele?.taxTypeForTally[0] === "UTGST"
           ? ele?.taxPercentForTally[0]
           : ""
       }</GSTRATE>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
       <GSTRATEDUTYHEAD>IGST</GSTRATEDUTYHEAD>
       <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
       <GSTRATE>  ${
         ele?.taxTypeForTally[0] === "IGST" ? ele?.taxPercentForTally[0] : ""
       }</GSTRATE>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
       <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
       <GSTRATEVALUATIONTYPE>&#4; Not Applicable</GSTRATEVALUATIONTYPE>
      </RATEDETAILS.LIST>
      <RATEDETAILS.LIST>
       <GSTRATEDUTYHEAD>State Cess</GSTRATEDUTYHEAD>
       <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
      </RATEDETAILS.LIST>
      <SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
      <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
      <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
      <EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
      <EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
     </ALLINVENTORYENTRIES.LIST>`;

    let totalTaxPercent = 0;
    let totalAmount = ele?.rateForTally * ele?.quantityForTally;

    ele?.taxTypeForTally?.map((gst, index) => {
      let taxPercent = ele?.taxPercentForTally[index];
      totalTaxPercent += taxPercent;
      if (ledgerDataArray.length) {
        let flag = false;
        let ledgerindex = 0;
        for (let i = 0; i < ledgerDataArray.length; i++) {
          if (
            ledgerDataArray[i].taxPercent === taxPercent &&
            ledgerDataArray[i].taxType === ele?.taxTypeForTally[index]
          ) {
            flag = true;
            ledgerindex = i;
          }
        }
        if (!flag) {
          ledgerDataArray.push({
            taxPercent: taxPercent,
            taxType: ele?.taxTypeForTally[index],
            taxAmount:
              (ele?.rateForTally * ele?.quantityForTally * taxPercent) / 100,
          });
        } else {
          ledgerDataArray[ledgerindex].taxAmount +=
            (ele?.rateForTally * ele?.quantityForTally * taxPercent) / 100;
        }
      } else {
        ledgerDataArray.push({
          taxPercent: taxPercent,
          taxType: ele?.taxTypeForTally[index],
          taxAmount:
            (ele?.rateForTally * ele?.quantityForTally * taxPercent) / 100,
        });
      }
    });
    totalTaxAmount += totalAmount + (totalAmount * totalTaxPercent) / 100;
  });
  console.log(totalTaxAmount, "totalTaxAmount");
  ledgerDataArray?.map((ele) => {
    ledgerData += `
    <LEDGERENTRIES.LIST>
    <OLDAUDITENTRYIDS.LIST TYPE="Number">
     <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
    </OLDAUDITENTRYIDS.LIST>
    <RATEOFINVOICETAX.LIST TYPE="Number">
     <RATEOFINVOICETAX> ${ele.taxPercent}</RATEOFINVOICETAX>
    </RATEOFINVOICETAX.LIST>
    <APPROPRIATEFOR>&#4; Not Applicable</APPROPRIATEFOR>
    <ROUNDTYPE>&#4; Not Applicable</ROUNDTYPE>
     <LEDGERNAME>${ele.taxType} ${ele?.taxPercent}%</LEDGERNAME>
    <GSTCLASS>&#4; Not Applicable</GSTCLASS>
    <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
    <LEDGERFROMITEM>No</LEDGERFROMITEM>
    <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
    <ISPARTYLEDGER>No</ISPARTYLEDGER>
    <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
    <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
    <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
    <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
    <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
    <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
    <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
    <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
    <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
    <AMOUNT>${ele?.taxAmount}</AMOUNT>
    <VATEXPAMOUNT>${ele?.taxAmount}</VATEXPAMOUNT>
    <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
    <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
    <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
    <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
    <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
    <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
    <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
    <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
    <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
    <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
    <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
    <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
    <CENVATDUTYALLOCATIONS.LIST>       </CENVATDUTYALLOCATIONS.LIST>
    <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
    <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
    <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
    <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
    <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
    <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
    <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
    <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
    <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
    <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
    <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
    <TAXTYPEALLOCATIONS.LIST>       </TAXTYPEALLOCATIONS.LIST>
   </LEDGERENTRIES.LIST>`;
  });

  // console.log(totalTaxAmount, "totalTaxAmount");

  //   `;

  let xmlData = `<ENVELOPE>
  <HEADER>
   <TALLYREQUEST>Import Data</TALLYREQUEST>
  </HEADER>
  <BODY>
   <IMPORTDATA>
    <REQUESTDESC>
     <REPORTNAME>All Masters</REPORTNAME>
     <STATICVARIABLES>
      <SVCURRENTCOMPANY>PROVISTA SOLUTIONS PVT LTD - (from 1-Apr-24)</SVCURRENTCOMPANY>
     </STATICVARIABLES>
    </REQUESTDESC>
    <REQUESTDATA>
    
     <TALLYMESSAGE xmlns:UDF="TallyUDF">
      <VOUCHER REMOTEID="4ccfb29f-4861-4411-95d8-ab91432bea7c-0000667c" VCHKEY="4ccfb29f-4861-4411-95d8-ab91432bea7c-0000b17b:00000008" VCHTYPE="Sales" ACTION="Create" OBJVIEW="Invoice Voucher View">
       <ADDRESS.LIST TYPE="String">
        <ADDRESS>B-118, TOWER-B, 11TH FLOOR, ATS BOUQUET, SECTOR-132, Noida,</ADDRESS>
        <ADDRESS>Gautam Buddha Nagar, ${companyState}, 201301&#13;&#10;&#13;&#10;</ADDRESS>
       </ADDRESS.LIST>
       <BASICBUYERADDRESS.LIST TYPE="String">
        <BASICBUYERADDRESS>B-118, TOWER-B, 11TH FLOOR, ATS BOUQUET, SECTOR-132, Noida,</BASICBUYERADDRESS>
        <BASICBUYERADDRESS>Gautam Buddha Nagar, ${companyState}, 201301&#13;&#10;&#13;&#10;</BASICBUYERADDRESS>
       </BASICBUYERADDRESS.LIST>
       <OLDAUDITENTRYIDS.LIST TYPE="Number">
        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
       </OLDAUDITENTRYIDS.LIST>
      <DATE>${todaysDate}</DATE>
       <VCHSTATUSDATE>${todaysDate}</VCHSTATUSDATE>
       <GUID>4ccfb29f-4861-4411-95d8-ab91432bea7c-0000667c</GUID>
       <GSTREGISTRATIONTYPE>Regular</GSTREGISTRATIONTYPE>
       <VATDEALERTYPE>Regular</VATDEALERTYPE>
       <STATENAME>${companyState}</STATENAME>
       <OBJECTUPDATEACTION>Create</OBJECTUPDATEACTION>
       <COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
       <PARTYGSTIN>09AADCE5737E1ZN</PARTYGSTIN>
       <PLACEOFSUPPLY>${companyState}</PLACEOFSUPPLY>
       <PARTYNAME>${partyName}</PARTYNAME>
       <GSTREGISTRATION TAXTYPE="GST" TAXREGISTRATION="23AAGCP7384M1ZV">Madhya Pradesh Registration</GSTREGISTRATION>
       <CMPGSTIN>23AAGCP7384M1ZV</CMPGSTIN>
       <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
       <PARTYLEDGERNAME>${partyName}</PARTYLEDGERNAME>
       <VOUCHERNUMBER>PSPL/23-24/${soNumber}</VOUCHERNUMBER>
       <BASICBUYERNAME>${partyName}</BASICBUYERNAME>
       <CMPGSTREGISTRATIONTYPE>Regular</CMPGSTREGISTRATIONTYPE>
       <PARTYMAILINGNAME>${partyName}</PARTYMAILINGNAME>
       <PARTYPINCODE>201301</PARTYPINCODE>
       <CONSIGNEEGSTIN>09AADCE5737E1ZN</CONSIGNEEGSTIN>
       <CONSIGNEEMAILINGNAME>${partyName}</CONSIGNEEMAILINGNAME>
       <CONSIGNEEPINCODE>201301</CONSIGNEEPINCODE>
       <CONSIGNEESTATENAME>${companyState}</CONSIGNEESTATENAME>
       <CMPGSTSTATE>Madhya Pradesh</CMPGSTSTATE>
       <CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME>
       <BASICBASEPARTYNAME>${partyName}</BASICBASEPARTYNAME>
       <NUMBERINGSTYLE>Auto Renumber</NUMBERINGSTYLE>
       <CSTFORMISSUETYPE>&#4; Not Applicable</CSTFORMISSUETYPE>
       <CSTFORMRECVTYPE>&#4; Not Applicable</CSTFORMRECVTYPE>
       <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
       <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
       <VCHSTATUSTAXADJUSTMENT>Default</VCHSTATUSTAXADJUSTMENT>
       <VCHSTATUSVOUCHERTYPE>Sales</VCHSTATUSVOUCHERTYPE>
       <VCHSTATUSTAXUNIT>Madhya Pradesh Registration</VCHSTATUSTAXUNIT>
       <VCHGSTCLASS>&#4; Not Applicable</VCHGSTCLASS>
       <BUYERPINNUMBER>AADCE5737E</BUYERPINNUMBER>
       <CONSIGNEEPINNUMBER>AADCE5737E</CONSIGNEEPINNUMBER>
       <VCHENTRYMODE>Item Invoice</VCHENTRYMODE>
       <DIFFACTUALQTY>No</DIFFACTUALQTY>
       <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
       <ISDELETED>No</ISDELETED>
       <ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED>
       <ASORIGINAL>No</ASORIGINAL>
       <AUDITED>No</AUDITED>
       <ISCOMMONPARTY>No</ISCOMMONPARTY>
       <FORJOBCOSTING>No</FORJOBCOSTING>
       <ISOPTIONAL>No</ISOPTIONAL>
       <EFFECTIVEDATE>20240524</EFFECTIVEDATE>
       <USEFOREXCISE>No</USEFOREXCISE>
       <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
       <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
       <USEFORINTEREST>No</USEFORINTEREST>
       <USEFORGAINLOSS>No</USEFORGAINLOSS>
       <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
       <USEFORCOMPOUND>No</USEFORCOMPOUND>
       <USEFORSERVICETAX>No</USEFORSERVICETAX>
       <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
       <ISSYSTEM>No</ISSYSTEM>
       <ISFETCHEDONLY>No</ISFETCHEDONLY>
       <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
       <ISCANCELLED>No</ISCANCELLED>
       <ISONHOLD>No</ISONHOLD>
       <ISSUMMARY>No</ISSUMMARY>
       <ISECOMMERCESUPPLY>No</ISECOMMERCESUPPLY>
       <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
       <ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE>
       <IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION>
       <CMPGSTISOTHTERRITORYASSESSEE>No</CMPGSTISOTHTERRITORYASSESSEE>
       <PARTYGSTISOTHTERRITORYASSESSEE>No</PARTYGSTISOTHTERRITORYASSESSEE>
       <IRNJSONEXPORTED>No</IRNJSONEXPORTED>
       <IRNCANCELLED>No</IRNCANCELLED>
       <IGNOREGSTCONFLICTINMIG>No</IGNOREGSTCONFLICTINMIG>
       <ISOPBALTRANSACTION>No</ISOPBALTRANSACTION>
       <IGNOREGSTFORMATVALIDATION>No</IGNOREGSTFORMATVALIDATION>
       <ISELIGIBLEFORITC>Yes</ISELIGIBLEFORITC>
       <UPDATESUMMARYVALUES>No</UPDATESUMMARYVALUES>
       <ISEWAYBILLAPPLICABLE>No</ISEWAYBILLAPPLICABLE>
       <ISDELETEDRETAINED>No</ISDELETEDRETAINED>
       <ISNULL>No</ISNULL>
       <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
       <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
       <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
       <ISEXER1NOPOVERWRITE>No</ISEXER1NOPOVERWRITE>
       <ISEXF2NOPOVERWRITE>No</ISEXF2NOPOVERWRITE>
       <ISEXER3NOPOVERWRITE>No</ISEXER3NOPOVERWRITE>
       <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
       <EXCISEOPENING>No</EXCISEOPENING>
       <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
       <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
       <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
       <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
       <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
       <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
       <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
       <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
       <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
       <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
       <VATADVANCEPAYMENT>No</VATADVANCEPAYMENT>
       <VATADVPAY>No</VATADVPAY>
       <ISCSTDELCAREDGOODSSALES>No</ISCSTDELCAREDGOODSSALES>
       <ISVATRESTAXINV>No</ISVATRESTAXINV>
       <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
       <ISISDVOUCHER>No</ISISDVOUCHER>
       <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
       <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
       <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
       <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
       <ISGSTREFUND>No</ISGSTREFUND>
       <OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY>
       <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
       <VCHSTATUSISVCHNUMUSED>No</VCHSTATUSISVCHNUMUSED>
       <VCHGSTSTATUSISINCLUDED>Yes</VCHGSTSTATUSISINCLUDED>
       <VCHGSTSTATUSISUNCERTAIN>No</VCHGSTSTATUSISUNCERTAIN>
       <VCHGSTSTATUSISEXCLUDED>No</VCHGSTSTATUSISEXCLUDED>
       <VCHGSTSTATUSISAPPLICABLE>Yes</VCHGSTSTATUSISAPPLICABLE>
       <VCHGSTSTATUSISGSTR2BRECONCILED>No</VCHGSTSTATUSISGSTR2BRECONCILED>
       <VCHGSTSTATUSISGSTR2BONLYINPORTAL>No</VCHGSTSTATUSISGSTR2BONLYINPORTAL>
       <VCHGSTSTATUSISGSTR2BONLYINBOOKS>No</VCHGSTSTATUSISGSTR2BONLYINBOOKS>
       <VCHGSTSTATUSISGSTR2BMISMATCH>No</VCHGSTSTATUSISGSTR2BMISMATCH>
       <VCHGSTSTATUSISGSTR2BINDIFFPERIOD>No</VCHGSTSTATUSISGSTR2BINDIFFPERIOD>
       <VCHGSTSTATUSISRETEFFDATEOVERRDN>No</VCHGSTSTATUSISRETEFFDATEOVERRDN>
       <VCHGSTSTATUSISOVERRDN>No</VCHGSTSTATUSISOVERRDN>
       <VCHGSTSTATUSISSTATINDIFFDATE>No</VCHGSTSTATUSISSTATINDIFFDATE>
       <VCHGSTSTATUSISRETINDIFFDATE>No</VCHGSTSTATUSISRETINDIFFDATE>
       <VCHGSTSTATUSMAINSECTIONEXCLUDED>No</VCHGSTSTATUSMAINSECTIONEXCLUDED>
       <VCHGSTSTATUSISBRANCHTRANSFEROUT>No</VCHGSTSTATUSISBRANCHTRANSFEROUT>
       <VCHGSTSTATUSISSYSTEMSUMMARY>No</VCHGSTSTATUSISSYSTEMSUMMARY>
       <VCHSTATUSISUNREGISTEREDRCM>No</VCHSTATUSISUNREGISTEREDRCM>
       <VCHSTATUSISOPTIONAL>No</VCHSTATUSISOPTIONAL>
       <VCHSTATUSISCANCELLED>No</VCHSTATUSISCANCELLED>
       <VCHSTATUSISDELETED>No</VCHSTATUSISDELETED>
       <VCHSTATUSISOPENINGBALANCE>No</VCHSTATUSISOPENINGBALANCE>
       <VCHSTATUSISFETCHEDONLY>No</VCHSTATUSISFETCHEDONLY>
       <PAYMENTLINKHASMULTIREF>No</PAYMENTLINKHASMULTIREF>
       <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
       <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
       <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
       <HASCASHFLOW>No</HASCASHFLOW>
       <ISPOSTDATED>No</ISPOSTDATED>
       <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
       <ISINVOICE>Yes</ISINVOICE>
       <MFGJOURNAL>No</MFGJOURNAL>
       <HASDISCOUNTS>No</HASDISCOUNTS>
       <ASPAYSLIP>No</ASPAYSLIP>
       <ISCOSTCENTRE>No</ISCOSTCENTRE>
       <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
       <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
       <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
       <ISVOID>No</ISVOID>
       <ORDERLINESTATUS>No</ORDERLINESTATUS>
       <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
       <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
       <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
       <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
       <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
       <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
       <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
       <ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED>
       <CHANGEVCHMODE>No</CHANGEVCHMODE>
       <RESETIRNQRCODE>No</RESETIRNQRCODE>
       <ALTERID> 39673</ALTERID>
       <MASTERID> 26236</MASTERID>
       <VOUCHERKEY>195141839093768</VOUCHERKEY>
       <VOUCHERRETAINKEY>57</VOUCHERRETAINKEY>
       <VOUCHERNUMBERSERIES>Default</VOUCHERNUMBERSERIES>
       <UPDATEDDATETIME>20240524154048000</UPDATEDDATETIME>
       <EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>
       <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
       <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
       <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
       <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
       <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
       <GSTADVADJDETAILS.LIST>      </GSTADVADJDETAILS.LIST>
       ${myItems}
       <CONTRITRANS.LIST>      </CONTRITRANS.LIST>
       <EWAYBILLERRORLIST.LIST>      </EWAYBILLERRORLIST.LIST>
       <IRNERRORLIST.LIST>      </IRNERRORLIST.LIST>
       <HARYANAVAT.LIST>      </HARYANAVAT.LIST>
       <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
       <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
       <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
       <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
       <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
       <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
       <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
       <LEDGERENTRIES.LIST>
        <OLDAUDITENTRYIDS.LIST TYPE="Number">
         <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
        </OLDAUDITENTRYIDS.LIST>
        <LEDGERNAME>${partyName}</LEDGERNAME>
        <GSTCLASS>&#4; Not Applicable</GSTCLASS>
        <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
        <LEDGERFROMITEM>No</LEDGERFROMITEM>
        <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
        <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
        <GSTOVERRIDDEN>No</GSTOVERRIDDEN>
        <ISGSTASSESSABLEVALUEOVERRIDDEN>No</ISGSTASSESSABLEVALUEOVERRIDDEN>
        <STRDISGSTAPPLICABLE>No</STRDISGSTAPPLICABLE>
        <STRDGSTISPARTYLEDGER>No</STRDGSTISPARTYLEDGER>
        <STRDGSTISDUTYLEDGER>No</STRDGSTISDUTYLEDGER>
        <CONTENTNEGISPOS>No</CONTENTNEGISPOS>
        <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
        <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
        <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
       <AMOUNT>-${totalTaxAmount}</AMOUNT>
        <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
        <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
        <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
        <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
        <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
        <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
        <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
        <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
        <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
        <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
        <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
        <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
        <CENVATDUTYALLOCATIONS.LIST>       </CENVATDUTYALLOCATIONS.LIST>
        <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
        <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
        <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
        <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
        <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
        <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
        <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
        <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
        <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
        <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
        <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
        <TAXTYPEALLOCATIONS.LIST>       </TAXTYPEALLOCATIONS.LIST>
       </LEDGERENTRIES.LIST>
      ${ledgerData}
       <GST.LIST>
        <PURPOSETYPE>GST</PURPOSETYPE>
        <STAT.LIST>
         <PURPOSETYPE>GST</PURPOSETYPE>
         <STATKEY>20245691Outward InvoicePSPL/23-24/${soNumber}</STATKEY>
         <ISFETCHEDONLY>No</ISFETCHEDONLY>
         <ISDELETED>No</ISDELETED>
         <TALLYCONTENTUSER.LIST>        </TALLYCONTENTUSER.LIST>
        </STAT.LIST>
       </GST.LIST>
       <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
       <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
       <GSTEWAYCONSIGNORADDRESS.LIST>      </GSTEWAYCONSIGNORADDRESS.LIST>
       <GSTEWAYCONSIGNEEADDRESS.LIST>      </GSTEWAYCONSIGNEEADDRESS.LIST>
       <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
       <TEMPGSTADVADJUSTED.LIST>      </TEMPGSTADVADJUSTED.LIST>
      </VOUCHER>
     </TALLYMESSAGE>
     <TALLYMESSAGE xmlns:UDF="TallyUDF">
      <COMPANY>
       <REMOTECMPINFO.LIST MERGE="Yes">
        <NAME>4ccfb29f-4861-4411-95d8-ab91432bea7c</NAME>
        <REMOTECMPNAME>PROVISTA SOLUTIONS PVT LTD - (from 1-Apr-24)</REMOTECMPNAME>
        <REMOTECMPSTATE>Madhya Pradesh</REMOTECMPSTATE>
       </REMOTECMPINFO.LIST>
      </COMPANY>
     </TALLYMESSAGE>
    </REQUESTDATA>
   </IMPORTDATA>
  </BODY>
 </ENVELOPE>
 
 

`;

  return xmlData;
};

module.exports = {
  SalesOrderXmlData,
};
